[project]
name = "langchain-first-d"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "gannak1", email = "gi676788@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "langchain>=1.4.0",
    "langchain-ollama>=1.1.0",
    "langgraph>=1.2.11",
    "uvicorn[standard]>=0.52.4",
]

[project.scripts]
langchain-first-d = "langchain_first_d:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
